export const projects = [
  {
    title: 'Vita Life Story',
    description: "Group project using Python, Django, SQL, and AWS to create a photo sharing app",
      image: 'https://i.imgur.com/g97RV6k.png',
      tags: ['Python', 'Django', 'SQL', 'AWS'],
    code: 'https://github.com/hummingbirdcreative/Vita-App.git',
    live: 'https://vita-life-story.herokuapp.com/',
    id: 0,
  },
  {
    title: 'Record Crate',
    description: "My first MERN application using Node.js, MongoDB, Mongoose, Express and React",
    image: 'https://i.imgur.com/5J583XW.png',
    tags: ['React', 'Express', 'Mongoose', 'MongoDb', 'Node.js'],
    code: 'https://github.com/hummingbirdcreative/Project3-RecordCatalog-FrontEnd-.git',
    live: 'https://record-project.netlify.app/',
    id: 1,
  },
  {
    title: 'Wardrobe Catalog',
    description: "My first full-CRUD application using Node.js, MongoDb, Mongoose, Express, and EJS",
      image: 'https://i.imgur.com/bYQlMgb.png',
      tags: ['Node.js', 'MongoDb', 'Mongoose', 'Express', 'EJS'],
    code: 'https://github.com/hummingbirdcreative/project2_WardrobeCatalog.git',
    live: 'https://wardobe-catalog.herokuapp.com/users/login',
    id: 2,
  },
  {
    title: 'Clean Beauty',
    description: "Website displays and filters beauty products by type and “clean” tag making fetch calls to a beauty API",
    image: 'https://i.imgur.com/dm6XdK2.png',
    tags: ['HTML', 'CSS', 'Javascript'],
    code: 'https://github.com/hummingbirdcreative/project1_cleanbeauty.git',
    live: 'https://serene-cascaron-dc9f3f.netlify.app/#',
    id: 3,
  },
];